esphome:
  name: esphome-relay
  friendly_name: ESPHome Relay

esp32:
#   board: esp32dev
  board: nodemcu-32s
  framework:
    type: arduino
    version: latest

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aAY0fYv5Avc9gqClXa4mY8OGxyTouxCPXxOO8QNFj8U="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esphome-relay"
    password: "L0g!tech"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: 32
      inverted: true
    name: "IN1" 
    id: IN1
  - platform: gpio 
    pin:
      number: 33
      inverted: true
    name: "IN2"
    id: IN2
  - platform: gpio 
    pin:
      number: 25
      inverted: true
    name: "IN3" 
    id: IN3  
  - platform: gpio
    pin: 
      number: 26
      inverted: true
    name: "IN4" 
    id: IN4
  - platform: gpio 
    pin:
      number: 27
      inverted: true
    name: "IN5"
    id: IN5
  - platform: gpio 
    pin:
      number: 14
      inverted: true
    name: "IN6" 
    id: IN6
  - platform: gpio 
    pin: 
      number: 23
      inverted: true
    name: "IN7"
    id: IN7
  - platform: gpio 
    pin:
      number: 22
      inverted: true
    name: "IN8" 
    id: IN8