# =============================
#  Mailbox Battery Low
# =============================
- platform: template
  sensors:
    mailbox_battery_low:
      value_template: "{{ states('sensor.mailbox_battery_mqtt')|float < 6.00 }}"

- platform: homeassistant
  id: master_bedroom_light_state
  entity_id: switch.master_bedroom_lights
  on_state:
    - lvgl.widget.update:
        id: master_bedroom_light_button
        checked: !lambda return x;

- platform: homeassistant
  id: master_bedroom_tv_state
  entity_id: master_bedroom_tv_light
  on_state:
    - lvgl.widget.update:
        id: master_bedroom_tv_button
        checked: !lambda return x;
