# ================================
# Mailbox Battery Voltage via MQTT
# ================================
- platform: mqtt
  name: "Mailbox Battery MQTT"
  state_topic: "mailbox_sensor/sensor/mailbox_battery/state"
  unit_of_measurement: "V"
  value_template: >
    "{{ (value | float) | round(2) }}"
  qos: "2"
  icon: mdi:battery-70

# ================================
# Time & Date
# ================================
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

# ================================
# Battery Level (%)
# ================================
- platform: template
  sensors:
    battery_level:
      friendly_name: "Battery Level"
      unit_of_measurement: "%"
      device_class: battery
      value_template: >
        {% set v = (states('sensor.battery_voltage') | float) %}
        {% set percent = ((v - 3.0) / (4.2 - 3.0) * 100) %}
        {{ [percent|int, 100]|min }}
