esphome:
  name: energy-meter
  friendly_name: energy-meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "w+Pal31wkLA9AdxiLQKywqETDJXl8i3NN5xQtXRmiTA="

ota:
  - platform: esphome
    password: "6c2a90852c1c2b8d7ff6e5f320ad86a1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Energy-Meter Fallback Hotspot"
    password: "7LtMRffywPSd"

captive_portal:
    