esphome:
  name: esp32-mailbox

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aAY0fYv5Avc9gqClXa4mY8OGxyTouxCPXxOO8QNFj8U="

ota:
  - platform: esphome
    password: "L1ttl3greenm3n"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mailbox"
    password: !secret ap_pw

captive_portal:

binary_sensor:
  - platform: status
    name: "Mailbox Sensor Status"

  - platform: gpio
    filters:
      - delayed_on_off: 200ms
    pin:
      allow_other_uses: true
      number: GPIO13
      mode: INPUT_PULLUP
    name: "Mailbox"
    device_class: door

sensor:
  - platform: adc
    pin: GPIO34
    name: "Mailbox Battery"
    attenuation: 12db
    update_interval: 30s
    filters:
      - calibrate_linear:
        - 3.05 -> 6.8
        - 3.30 -> 7.0
        - 3.45 -> 7.2
        - 3.60 -> 7.4
        - 3.75 -> 7.6
        - 3.90 -> 8.0

deep_sleep:
  run_duration: 90s
  wakeup_pin:
    number: GPIO13
    allow_other_uses: true
    mode: INPUT_PULLUP
  id: mail_deep_sleep

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_un
  password: !secret mqtt_pw
  discovery: false
  discovery_retain: false

switch:
  - platform: gpio
    pin: GPIO2
    name: "Onboard LED"
    id: onboard_led
    restore_mode: ALWAYS_OFF
